linters:
  enable:
    - gofmt
    - govet
    - gocyclo
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters

run:
  deadline: 5m
  tests: true

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0 
  exclude-dirs:
    - example/
